<?php


namespace Betweenapp\Backend\Tests\Features;


use Betweenapp\Backend\Tests\FeatureTestCase;

class SimpleTest extends FeatureTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_tests_are_working()
    {
        $this->assertTrue(true);
    }

}
